In [6]:
from sklearn.datasets import load_boston        
import pandas as pd     

boston = load_boston() # データセットの読み込み      
df = pd.DataFrame(boston.data,columns=boston.feature_names)
df["test_data"] = "test_data_val"       
df.loc[df.NOX < 0.5, "NOX"]=None # NaN値作成のため更新
# 以下Ptyhon内のコードを記載し、実行
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,test_data
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,test_data_val
1,0.02731,0.0,7.07,0.0,NaN,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,test_data_val
2,0.02729,0.0,7.07,0.0,NaN,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,test_data_val
3,0.03237,0.0,2.18,0.0,NaN,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,test_data_val
4,0.06905,0.0,2.18,0.0,NaN,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,test_data_val
5,0.02985,0.0,2.18,0.0,NaN,6.430,58.7,6.0622,3.0,222.0,18.7,394.12,5.21,test_data_val
6,0.08829,12.5,7.87,0.0,0.524,6.012,66.6,5.5605,5.0,311.0,15.2,395.60,12.43,test_data_val
7,0.14455,12.5,7.87,0.0,0.524,6.172,96.1,5.9505,5.0,311.0,15.2,396.90,19.15,test_data_val
8,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,15.2,386.63,29.93,test_data_val
9,0.17004,12.5,7.87,0.0,0.524,6.004,85.9,6.5921,5.0,311.0,15.2,386.71,17.10,test_data_val
10,0.22489,12.5,7.87,0.0,0.524,6.377,94.3,6.3467,5.0,311.0,15.2,392.52,20.45,test_data_val
11,0.11747,12.5,7.87,0.0,0.524,6.009,82.9,6.2267,5.0,311.0,15.2,396.90,13.27,test_data_val
12,0.09378,12.5,7.87,0.0,0.524,5.889,39.0,5.4509,5.0,311.0,15.2,390.50,15.71,test_data_val
13,0.62976,0.0,8.14,0.0,0.538,5.949,61.8,4.7075,4.0,307.0,21.0,396.90,8.26,test_data_val
14,0.63796,0.0,8.14,0.0,0.538,6.096,84.5,4.4619,4.0,307.0,21.0,380.02,10.26,test_data_val
15,0.62739,0.0,8.14,0.0,0.538,5.834,56.5,4.4986,4.0,307.0,21.0,395.62,8.47,test_data_val
16,1.05393,0.0,8.14,0.0,0.538,5.935,29.3,4.4986,4.0,307.0,21.0,386.85,6.58,test_data_val
17,0.78420,0.0,8.14,0.0,0.538,5.990,81.7,4.2579,4.0,307.0,21.0,386.75,14.67,test_data_val
18,0.80271,0.0,8.14,0.0,0.538,5.456,36.6,3.7965,4.0,307.0,21.0,288.99,11.69,test_data_val
19,0.72580,0.0,8.14,0.0,0.538,5.727,69.5,3.7965,4.0,307.0,21.0,390.95,11.28,test_data_val
20,1.25179,0.0,8.14,0.0,0.538,5.570,98.1,3.7979,4.0,307.0,21.0,376.57,21.02,test_data_val
21,0.85204,0.0,8.14,0.0,0.538,5.965,89.2,4.0123,4.0,307.0,21.0,392.53,13.83,test_data_val
22,1.23247,0.0,8.14,0.0,0.538,6.142,91.7,3.9769,4.0,307.0,21.0,396.90,18.72,test_data_val
23,0.98843,0.0,8.14,0.0,0.538,5.813,100.0,4.0952,4.0,307.0,21.0,394.54,19.88,test_data_val
24,0.75026,0.0,8.14,0.0,0.538,5.924,94.1,4.3996,4.0,307.0,21.0,394.33,16.30,test_data_val
25,0.84054,0.0,8.14,0.0,0.538,5.599,85.7,4.4546,4.0,307.0,21.0,303.42,16.51,test_data_val
26,0.67191,0.0,8.14,0.0,0.538,5.813,90.3,4.6820,4.0,307.0,21.0,376.88,14.81,test_data_val
27,0.95577,0.0,8.14,0.0,0.538,6.047,88.8,4.4534,4.0,307.0,21.0,306.38,17.28,test_data_val
28,0.77299,0.0,8.14,0.0,0.538,6.495,94.4,4.4547,4.0,307.0,21.0,387.94,12.80,test_data_val
29,1.00245,0.0,8.14,0.0,0.538,6.674,87.3,4.2390,4.0,307.0,21.0,380.23,11.98,test_data_val
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,4.87141,0.0,18.10,0.0,0.614,6.484,93.6,2.3053,24.0,666.0,20.2,396.21,18.68,test_data_val
477,15.02340,0.0,18.10,0.0,0.614,5.304,97.3,2.1007,24.0,666.0,20.2,349.48,24.91,test_data_val
478,10.23300,0.0,18.10,0.0,0.614,6.185,96.7,2.1705,24.0,666.0,20.2,379.70,18.03,test_data_val
479,14.33370,0.0,18.10,0.0,0.614,6.229,88.0,1.9512,24.0,666.0,20.2,383.32,13.11,test_data_val
480,5.82401,0.0,18.10,0.0,0.532,6.242,64.7,3.4242,24.0,666.0,20.2,396.90,10.74,test_data_val
481,5.70818,0.0,18.10,0.0,0.532,6.750,74.9,3.3317,24.0,666.0,20.2,393.07,7.74,test_data_val
482,5.73116,0.0,18.10,0.0,0.532,7.061,77.0,3.4106,24.0,666.0,20.2,395.28,7.01,test_data_val
483,2.81838,0.0,18.10,0.0,0.532,5.762,40.3,4.0983,24.0,666.0,20.2,392.92,10.42,test_data_val
484,2.37857,0.0,18.10,0.0,0.583,5.871,41.9,3.7240,24.0,666.0,20.2,370.73,13.34,test_data_val
485,3.67367,0.0,18.10,0.0,0.583,6.312,51.9,3.9917,24.0,666.0,20.2,388.62,10.58,test_data_val
486,5.69175,0.0,18.10,0.0,0.583,6.114,79.8,3.5459,24.0,666.0,20.2,392.68,14.98,test_data_val
487,4.83567,0.0,18.10,0.0,0.583,5.905,53.2,3.1523,24.0,666.0,20.2,388.22,11.45,test_data_val
488,0.15086,0.0,27.74,0.0,0.609,5.454,92.7,1.8209,4.0,711.0,20.1,395.09,18.06,test_data_val
489,0.18337,0.0,27.74,0.0,0.609,5.414,98.3,1.7554,4.0,711.0,20.1,344.05,23.97,test_data_val
490,0.20746,0.0,27.74,0.0,0.609,5.093,98.0,1.8226,4.0,711.0,20.1,318.43,29.68,test_data_val
491,0.10574,0.0,27.74,0.0,0.609,5.983,98.8,1.8681,4.0,711.0,20.1,390.11,18.07,test_data_val
492,0.11132,0.0,27.74,0.0,0.609,5.983,83.5,2.1099,4.0,711.0,20.1,396.90,13.35,test_data_val
493,0.17331,0.0,9.69,0.0,0.585,5.707,54.0,2.3817,6.0,391.0,19.2,396.90,12.01,test_data_val
494,0.27957,0.0,9.69,0.0,0.585,5.926,42.6,2.3817,6.0,391.0,19.2,396.90,13.59,test_data_val
495,0.17899,0.0,9.69,0.0,0.585,5.670,28.8,2.7986,6.0,391.0,19.2,393.29,17.60,test_data_val
496,0.28960,0.0,9.69,0.0,0.585,5.390,72.9,2.7986,6.0,391.0,19.2,396.90,21.14,test_data_val
497,0.26838,0.0,9.69,0.0,0.585,5.794,70.6,2.8927,6.0,391.0,19.2,396.90,14.10,test_data_val
498,0.23912,0.0,9.69,0.0,0.585,6.019,65.3,2.4091,6.0,391.0,19.2,396.90,12.92,test_data_val
499,0.17783,0.0,9.69,0.0,0.585,5.569,73.5,2.3999,6.0,391.0,19.2,395.77,15.10,test_data_val
500,0.22438,0.0,9.69,0.0,0.585,6.027,79.7,2.4982,6.0,391.0,19.2,396.90,14.33,test_data_val
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67,test_data_val
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,test_data_val
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,test_data_val
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,test_data_val
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88,test_data_val

In [7]:
df[["RM", "AGE"]]

        RM    AGE
0    6.575   65.2
1    6.421   78.9
2    7.185   61.1
3    6.998   45.8
4    7.147   54.2
5    6.430   58.7
6    6.012   66.6
7    6.172   96.1
8    5.631  100.0
9    6.004   85.9
10   6.377   94.3
11   6.009   82.9
12   5.889   39.0
13   5.949   61.8
14   6.096   84.5
15   5.834   56.5
16   5.935   29.3
17   5.990   81.7
18   5.456   36.6
19   5.727   69.5
20   5.570   98.1
21   5.965   89.2
22   6.142   91.7
23   5.813  100.0
24   5.924   94.1
25   5.599   85.7
26   5.813   90.3
27   6.047   88.8
28   6.495   94.4
29   6.674   87.3
..     ...    ...
476  6.484   93.6
477  5.304   97.3
478  6.185   96.7
479  6.229   88.0
480  6.242   64.7
481  6.750   74.9
482  7.061   77.0
483  5.762   40.3
484  5.871   41.9
485  6.312   51.9
486  6.114   79.8
487  5.905   53.2
488  5.454   92.7
489  5.414   98.3
490  5.093   98.0
491  5.983   98.8
492  5.983   83.5
493  5.707   54.0
494  5.926   42.6
495  5.670   28.8
496  5.390   72.9
497  5.794   70.6
498  6.019   65.3
499  5.569   73.5
500  6.027   79.7
501  6.593   69.1
502  6.120   76.7
503  6.976   91.0
504  6.794   89.3
505  6.030   80.8

[506 rows x 2 columns]

In [8]:
df.rename(columns={"RM":"af_rm", "AGE":"af_age"}, inplace=True)
df
df.rename(columns={"af_rm":"RM", "af_age":"AGE"}, inplace=True)

In [9]:
df["flg"] = "1"
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,test_data,flg
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,test_data_val,1
1,0.02731,0.0,7.07,0.0,NaN,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,test_data_val,1
2,0.02729,0.0,7.07,0.0,NaN,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,test_data_val,1
3,0.03237,0.0,2.18,0.0,NaN,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,test_data_val,1
4,0.06905,0.0,2.18,0.0,NaN,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,test_data_val,1
5,0.02985,0.0,2.18,0.0,NaN,6.430,58.7,6.0622,3.0,222.0,18.7,394.12,5.21,test_data_val,1
6,0.08829,12.5,7.87,0.0,0.524,6.012,66.6,5.5605,5.0,311.0,15.2,395.60,12.43,test_data_val,1
7,0.14455,12.5,7.87,0.0,0.524,6.172,96.1,5.9505,5.0,311.0,15.2,396.90,19.15,test_data_val,1
8,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,15.2,386.63,29.93,test_data_val,1
9,0.17004,12.5,7.87,0.0,0.524,6.004,85.9,6.5921,5.0,311.0,15.2,386.71,17.10,test_data_val,1
10,0.22489,12.5,7.87,0.0,0.524,6.377,94.3,6.3467,5.0,311.0,15.2,392.52,20.45,test_data_val,1
11,0.11747,12.5,7.87,0.0,0.524,6.009,82.9,6.2267,5.0,311.0,15.2,396.90,13.27,test_data_val,1
12,0.09378,12.5,7.87,0.0,0.524,5.889,39.0,5.4509,5.0,311.0,15.2,390.50,15.71,test_data_val,1
13,0.62976,0.0,8.14,0.0,0.538,5.949,61.8,4.7075,4.0,307.0,21.0,396.90,8.26,test_data_val,1
14,0.63796,0.0,8.14,0.0,0.538,6.096,84.5,4.4619,4.0,307.0,21.0,380.02,10.26,test_data_val,1
15,0.62739,0.0,8.14,0.0,0.538,5.834,56.5,4.4986,4.0,307.0,21.0,395.62,8.47,test_data_val,1
16,1.05393,0.0,8.14,0.0,0.538,5.935,29.3,4.4986,4.0,307.0,21.0,386.85,6.58,test_data_val,1
17,0.78420,0.0,8.14,0.0,0.538,5.990,81.7,4.2579,4.0,307.0,21.0,386.75,14.67,test_data_val,1
18,0.80271,0.0,8.14,0.0,0.538,5.456,36.6,3.7965,4.0,307.0,21.0,288.99,11.69,test_data_val,1
19,0.72580,0.0,8.14,0.0,0.538,5.727,69.5,3.7965,4.0,307.0,21.0,390.95,11.28,test_data_val,1
20,1.25179,0.0,8.14,0.0,0.538,5.570,98.1,3.7979,4.0,307.0,21.0,376.57,21.02,test_data_val,1
21,0.85204,0.0,8.14,0.0,0.538,5.965,89.2,4.0123,4.0,307.0,21.0,392.53,13.83,test_data_val,1
22,1.23247,0.0,8.14,0.0,0.538,6.142,91.7,3.9769,4.0,307.0,21.0,396.90,18.72,test_data_val,1
23,0.98843,0.0,8.14,0.0,0.538,5.813,100.0,4.0952,4.0,307.0,21.0,394.54,19.88,test_data_val,1
24,0.75026,0.0,8.14,0.0,0.538,5.924,94.1,4.3996,4.0,307.0,21.0,394.33,16.30,test_data_val,1
25,0.84054,0.0,8.14,0.0,0.538,5.599,85.7,4.4546,4.0,307.0,21.0,303.42,16.51,test_data_val,1
26,0.67191,0.0,8.14,0.0,0.538,5.813,90.3,4.6820,4.0,307.0,21.0,376.88,14.81,test_data_val,1
27,0.95577,0.0,8.14,0.0,0.538,6.047,88.8,4.4534,4.0,307.0,21.0,306.38,17.28,test_data_val,1
28,0.77299,0.0,8.14,0.0,0.538,6.495,94.4,4.4547,4.0,307.0,21.0,387.94,12.80,test_data_val,1
29,1.00245,0.0,8.14,0.0,0.538,6.674,87.3,4.2390,4.0,307.0,21.0,380.23,11.98,test_data_val,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,4.87141,0.0,18.10,0.0,0.614,6.484,93.6,2.3053,24.0,666.0,20.2,396.21,18.68,test_data_val,1
477,15.02340,0.0,18.10,0.0,0.614,5.304,97.3,2.1007,24.0,666.0,20.2,349.48,24.91,test_data_val,1
478,10.23300,0.0,18.10,0.0,0.614,6.185,96.7,2.1705,24.0,666.0,20.2,379.70,18.03,test_data_val,1
479,14.33370,0.0,18.10,0.0,0.614,6.229,88.0,1.9512,24.0,666.0,20.2,383.32,13.11,test_data_val,1
480,5.82401,0.0,18.10,0.0,0.532,6.242,64.7,3.4242,24.0,666.0,20.2,396.90,10.74,test_data_val,1
481,5.70818,0.0,18.10,0.0,0.532,6.750,74.9,3.3317,24.0,666.0,20.2,393.07,7.74,test_data_val,1
482,5.73116,0.0,18.10,0.0,0.532,7.061,77.0,3.4106,24.0,666.0,20.2,395.28,7.01,test_data_val,1
483,2.81838,0.0,18.10,0.0,0.532,5.762,40.3,4.0983,24.0,666.0,20.2,392.92,10.42,test_data_val,1
484,2.37857,0.0,18.10,0.0,0.583,5.871,41.9,3.7240,24.0,666.0,20.2,370.73,13.34,test_data_val,1
485,3.67367,0.0,18.10,0.0,0.583,6.312,51.9,3.9917,24.0,666.0,20.2,388.62,10.58,test_data_val,1
486,5.69175,0.0,18.10,0.0,0.583,6.114,79.8,3.5459,24.0,666.0,20.2,392.68,14.98,test_data_val,1
487,4.83567,0.0,18.10,0.0,0.583,5.905,53.2,3.1523,24.0,666.0,20.2,388.22,11.45,test_data_val,1
488,0.15086,0.0,27.74,0.0,0.609,5.454,92.7,1.8209,4.0,711.0,20.1,395.09,18.06,test_data_val,1
489,0.18337,0.0,27.74,0.0,0.609,5.414,98.3,1.7554,4.0,711.0,20.1,344.05,23.97,test_data_val,1
490,0.20746,0.0,27.74,0.0,0.609,5.093,98.0,1.8226,4.0,711.0,20.1,318.43,29.68,test_data_val,1
491,0.10574,0.0,27.74,0.0,0.609,5.983,98.8,1.8681,4.0,711.0,20.1,390.11,18.07,test_data_val,1
492,0.11132,0.0,27.74,0.0,0.609,5.983,83.5,2.1099,4.0,711.0,20.1,396.90,13.35,test_data_val,1
493,0.17331,0.0,9.69,0.0,0.585,5.707,54.0,2.3817,6.0,391.0,19.2,396.90,12.01,test_data_val,1
494,0.27957,0.0,9.69,0.0,0.585,5.926,42.6,2.3817,6.0,391.0,19.2,396.90,13.59,test_data_val,1
495,0.17899,0.0,9.69,0.0,0.585,5.670,28.8,2.7986,6.0,391.0,19.2,393.29,17.60,test_data_val,1
496,0.28960,0.0,9.69,0.0,0.585,5.390,72.9,2.7986,6.0,391.0,19.2,396.90,21.14,test_data_val,1
497,0.26838,0.0,9.69,0.0,0.585,5.794,70.6,2.8927,6.0,391.0,19.2,396.90,14.10,test_data_val,1
498,0.23912,0.0,9.69,0.0,0.585,6.019,65.3,2.4091,6.0,391.0,19.2,396.90,12.92,test_data_val,1
499,0.17783,0.0,9.69,0.0,0.585,5.569,73.5,2.3999,6.0,391.0,19.2,395.77,15.10,test_data_val,1
500,0.22438,0.0,9.69,0.0,0.585,6.027,79.7,2.4982,6.0,391.0,19.2,396.90,14.33,test_data_val,1
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67,test_data_val,1
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,test_data_val,1
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,test_data_val,1
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,test_data_val,1
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88,test_data_val,1

In [10]:
df[df["RM"] > 6]

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,test_data,flg
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,test_data_val,1
1,0.02731,0.0,7.07,0.0,NaN,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,test_data_val,1
2,0.02729,0.0,7.07,0.0,NaN,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,test_data_val,1
3,0.03237,0.0,2.18,0.0,NaN,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,test_data_val,1
4,0.06905,0.0,2.18,0.0,NaN,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,test_data_val,1
5,0.02985,0.0,2.18,0.0,NaN,6.430,58.7,6.0622,3.0,222.0,18.7,394.12,5.21,test_data_val,1
6,0.08829,12.5,7.87,0.0,0.524,6.012,66.6,5.5605,5.0,311.0,15.2,395.60,12.43,test_data_val,1
7,0.14455,12.5,7.87,0.0,0.524,6.172,96.1,5.9505,5.0,311.0,15.2,396.90,19.15,test_data_val,1
9,0.17004,12.5,7.87,0.0,0.524,6.004,85.9,6.5921,5.0,311.0,15.2,386.71,17.10,test_data_val,1
10,0.22489,12.5,7.87,0.0,0.524,6.377,94.3,6.3467,5.0,311.0,15.2,392.52,20.45,test_data_val,1
11,0.11747,12.5,7.87,0.0,0.524,6.009,82.9,6.2267,5.0,311.0,15.2,396.90,13.27,test_data_val,1
14,0.63796,0.0,8.14,0.0,0.538,6.096,84.5,4.4619,4.0,307.0,21.0,380.02,10.26,test_data_val,1
22,1.23247,0.0,8.14,0.0,0.538,6.142,91.7,3.9769,4.0,307.0,21.0,396.90,18.72,test_data_val,1
27,0.95577,0.0,8.14,0.0,0.538,6.047,88.8,4.4534,4.0,307.0,21.0,306.38,17.28,test_data_val,1
28,0.77299,0.0,8.14,0.0,0.538,6.495,94.4,4.4547,4.0,307.0,21.0,387.94,12.80,test_data_val,1
29,1.00245,0.0,8.14,0.0,0.538,6.674,87.3,4.2390,4.0,307.0,21.0,380.23,11.98,test_data_val,1
31,1.35472,0.0,8.14,0.0,0.538,6.072,100.0,4.1750,4.0,307.0,21.0,376.73,13.04,test_data_val,1
34,1.61282,0.0,8.14,0.0,0.538,6.096,96.9,3.7598,4.0,307.0,21.0,248.31,20.34,test_data_val,1
39,0.02763,75.0,2.95,0.0,NaN,6.595,21.8,5.4011,3.0,252.0,18.3,395.63,4.32,test_data_val,1
40,0.03359,75.0,2.95,0.0,NaN,7.024,15.8,5.4011,3.0,252.0,18.3,395.62,1.98,test_data_val,1
41,0.12744,0.0,6.91,0.0,NaN,6.770,2.9,5.7209,3.0,233.0,17.9,385.41,4.84,test_data_val,1
42,0.14150,0.0,6.91,0.0,NaN,6.169,6.6,5.7209,3.0,233.0,17.9,383.37,5.81,test_data_val,1
43,0.15936,0.0,6.91,0.0,NaN,6.211,6.5,5.7209,3.0,233.0,17.9,394.46,7.44,test_data_val,1
44,0.12269,0.0,6.91,0.0,NaN,6.069,40.0,5.7209,3.0,233.0,17.9,389.39,9.55,test_data_val,1
47,0.22927,0.0,6.91,0.0,NaN,6.030,85.5,5.6894,3.0,233.0,17.9,392.74,18.80,test_data_val,1
51,0.04337,21.0,5.64,0.0,NaN,6.115,63.0,6.8147,4.0,243.0,16.8,393.97,9.43,test_data_val,1
52,0.05360,21.0,5.64,0.0,NaN,6.511,21.1,6.8147,4.0,243.0,16.8,396.90,5.28,test_data_val,1
55,0.01311,90.0,1.22,0.0,NaN,7.249,21.9,8.6966,5.0,226.0,17.9,395.93,4.81,test_data_val,1
56,0.02055,85.0,0.74,0.0,NaN,6.383,35.7,9.1876,2.0,313.0,17.3,396.90,5.77,test_data_val,1
57,0.01432,100.0,1.32,0.0,NaN,6.816,40.5,8.3248,5.0,256.0,15.1,392.90,3.95,test_data_val,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
454,9.51363,0.0,18.10,0.0,0.713,6.728,94.1,2.4961,24.0,666.0,20.2,6.68,18.71,test_data_val,1
455,4.75237,0.0,18.10,0.0,0.713,6.525,86.5,2.4358,24.0,666.0,20.2,50.92,18.13,test_data_val,1
458,7.75223,0.0,18.10,0.0,0.713,6.301,83.7,2.7831,24.0,666.0,20.2,272.21,16.23,test_data_val,1
459,6.80117,0.0,18.10,0.0,0.713,6.081,84.4,2.7175,24.0,666.0,20.2,396.90,14.70,test_data_val,1
460,4.81213,0.0,18.10,0.0,0.713,6.701,90.0,2.5975,24.0,666.0,20.2,255.23,16.42,test_data_val,1
461,3.69311,0.0,18.10,0.0,0.713,6.376,88.4,2.5671,24.0,666.0,20.2,391.43,14.65,test_data_val,1
462,6.65492,0.0,18.10,0.0,0.713,6.317,83.0,2.7344,24.0,666.0,20.2,396.90,13.99,test_data_val,1
463,5.82115,0.0,18.10,0.0,0.713,6.513,89.9,2.8016,24.0,666.0,20.2,393.82,10.29,test_data_val,1
464,7.83932,0.0,18.10,0.0,0.655,6.209,65.4,2.9634,24.0,666.0,20.2,396.90,13.22,test_data_val,1
467,4.42228,0.0,18.10,0.0,0.584,6.003,94.5,2.5403,24.0,666.0,20.2,331.29,21.32,test_data_val,1
470,4.34879,0.0,18.10,0.0,0.580,6.167,84.0,3.0334,24.0,666.0,20.2,396.90,16.29,test_data_val,1
471,4.03841,0.0,18.10,0.0,0.532,6.229,90.7,3.0993,24.0,666.0,20.2,395.33,12.87,test_data_val,1
472,3.56868,0.0,18.10,0.0,0.580,6.437,75.0,2.8965,24.0,666.0,20.2,393.37,14.36,test_data_val,1
473,4.64689,0.0,18.10,0.0,0.614,6.980,67.6,2.5329,24.0,666.0,20.2,374.68,11.66,test_data_val,1
475,6.39312,0.0,18.10,0.0,0.584,6.162,97.4,2.2060,24.0,666.0,20.2,302.76,24.10,test_data_val,1
476,4.87141,0.0,18.10,0.0,0.614,6.484,93.6,2.3053,24.0,666.0,20.2,396.21,18.68,test_data_val,1
478,10.23300,0.0,18.10,0.0,0.614,6.185,96.7,2.1705,24.0,666.0,20.2,379.70,18.03,test_data_val,1
479,14.33370,0.0,18.10,0.0,0.614,6.229,88.0,1.9512,24.0,666.0,20.2,383.32,13.11,test_data_val,1
480,5.82401,0.0,18.10,0.0,0.532,6.242,64.7,3.4242,24.0,666.0,20.2,396.90,10.74,test_data_val,1
481,5.70818,0.0,18.10,0.0,0.532,6.750,74.9,3.3317,24.0,666.0,20.2,393.07,7.74,test_data_val,1
482,5.73116,0.0,18.10,0.0,0.532,7.061,77.0,3.4106,24.0,666.0,20.2,395.28,7.01,test_data_val,1
485,3.67367,0.0,18.10,0.0,0.583,6.312,51.9,3.9917,24.0,666.0,20.2,388.62,10.58,test_data_val,1
486,5.69175,0.0,18.10,0.0,0.583,6.114,79.8,3.5459,24.0,666.0,20.2,392.68,14.98,test_data_val,1
498,0.23912,0.0,9.69,0.0,0.585,6.019,65.3,2.4091,6.0,391.0,19.2,396.90,12.92,test_data_val,1
500,0.22438,0.0,9.69,0.0,0.585,6.027,79.7,2.4982,6.0,391.0,19.2,396.90,14.33,test_data_val,1
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67,test_data_val,1
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,test_data_val,1
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,test_data_val,1
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,test_data_val,1
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88,test_data_val,1

In [11]:
df[["RM", "AGE"]].query('RM > 6 and AGE == "100"')

        RM    AGE
31   6.072  100.0
145  6.130  100.0
158  6.066  100.0
159  6.510  100.0
258  7.333  100.0
259  6.842  100.0
371  6.216  100.0
379  6.223  100.0
401  6.343  100.0
402  6.404  100.0
409  6.852  100.0
411  6.657  100.0
415  6.434  100.0
420  6.411  100.0
437  6.152  100.0
442  6.219  100.0
443  6.485  100.0

In [12]:
df[df["NOX"].isnull()]

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,test_data,flg
1,0.02731,0.0,7.07,0.0,NaN,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,test_data_val,1
2,0.02729,0.0,7.07,0.0,NaN,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,test_data_val,1
3,0.03237,0.0,2.18,0.0,NaN,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,test_data_val,1
4,0.06905,0.0,2.18,0.0,NaN,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,test_data_val,1
5,0.02985,0.0,2.18,0.0,NaN,6.430,58.7,6.0622,3.0,222.0,18.7,394.12,5.21,test_data_val,1
35,0.06417,0.0,5.96,0.0,NaN,5.933,68.2,3.3603,5.0,279.0,19.2,396.90,9.68,test_data_val,1
36,0.09744,0.0,5.96,0.0,NaN,5.841,61.4,3.3779,5.0,279.0,19.2,377.56,11.41,test_data_val,1
37,0.08014,0.0,5.96,0.0,NaN,5.850,41.5,3.9342,5.0,279.0,19.2,396.90,8.77,test_data_val,1
38,0.17505,0.0,5.96,0.0,NaN,5.966,30.2,3.8473,5.0,279.0,19.2,393.43,10.13,test_data_val,1
39,0.02763,75.0,2.95,0.0,NaN,6.595,21.8,5.4011,3.0,252.0,18.3,395.63,4.32,test_data_val,1
40,0.03359,75.0,2.95,0.0,NaN,7.024,15.8,5.4011,3.0,252.0,18.3,395.62,1.98,test_data_val,1
41,0.12744,0.0,6.91,0.0,NaN,6.770,2.9,5.7209,3.0,233.0,17.9,385.41,4.84,test_data_val,1
42,0.14150,0.0,6.91,0.0,NaN,6.169,6.6,5.7209,3.0,233.0,17.9,383.37,5.81,test_data_val,1
43,0.15936,0.0,6.91,0.0,NaN,6.211,6.5,5.7209,3.0,233.0,17.9,394.46,7.44,test_data_val,1
44,0.12269,0.0,6.91,0.0,NaN,6.069,40.0,5.7209,3.0,233.0,17.9,389.39,9.55,test_data_val,1
45,0.17142,0.0,6.91,0.0,NaN,5.682,33.8,5.1004,3.0,233.0,17.9,396.90,10.21,test_data_val,1
46,0.18836,0.0,6.91,0.0,NaN,5.786,33.3,5.1004,3.0,233.0,17.9,396.90,14.15,test_data_val,1
47,0.22927,0.0,6.91,0.0,NaN,6.030,85.5,5.6894,3.0,233.0,17.9,392.74,18.80,test_data_val,1
48,0.25387,0.0,6.91,0.0,NaN,5.399,95.3,5.8700,3.0,233.0,17.9,396.90,30.81,test_data_val,1
49,0.21977,0.0,6.91,0.0,NaN,5.602,62.0,6.0877,3.0,233.0,17.9,396.90,16.20,test_data_val,1
50,0.08873,21.0,5.64,0.0,NaN,5.963,45.7,6.8147,4.0,243.0,16.8,395.56,13.45,test_data_val,1
51,0.04337,21.0,5.64,0.0,NaN,6.115,63.0,6.8147,4.0,243.0,16.8,393.97,9.43,test_data_val,1
52,0.05360,21.0,5.64,0.0,NaN,6.511,21.1,6.8147,4.0,243.0,16.8,396.90,5.28,test_data_val,1
53,0.04981,21.0,5.64,0.0,NaN,5.998,21.4,6.8147,4.0,243.0,16.8,396.90,8.43,test_data_val,1
54,0.01360,75.0,4.00,0.0,NaN,5.888,47.6,7.3197,3.0,469.0,21.1,396.90,14.80,test_data_val,1
55,0.01311,90.0,1.22,0.0,NaN,7.249,21.9,8.6966,5.0,226.0,17.9,395.93,4.81,test_data_val,1
56,0.02055,85.0,0.74,0.0,NaN,6.383,35.7,9.1876,2.0,313.0,17.3,396.90,5.77,test_data_val,1
57,0.01432,100.0,1.32,0.0,NaN,6.816,40.5,8.3248,5.0,256.0,15.1,392.90,3.95,test_data_val,1
58,0.15445,25.0,5.13,0.0,NaN,6.145,29.2,7.8148,8.0,284.0,19.7,390.68,6.86,test_data_val,1
59,0.10328,25.0,5.13,0.0,NaN,5.927,47.2,6.9320,8.0,284.0,19.7,396.90,9.22,test_data_val,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,0.05479,33.0,2.18,0.0,NaN,6.616,58.1,3.3700,7.0,222.0,18.4,393.36,8.93,test_data_val,1
306,0.07503,33.0,2.18,0.0,NaN,7.420,71.9,3.0992,7.0,222.0,18.4,396.90,6.47,test_data_val,1
307,0.04932,33.0,2.18,0.0,NaN,6.849,70.3,3.1827,7.0,222.0,18.4,396.90,7.53,test_data_val,1
320,0.16760,0.0,7.38,0.0,NaN,6.426,52.3,4.5404,5.0,287.0,19.6,396.90,7.20,test_data_val,1
321,0.18159,0.0,7.38,0.0,NaN,6.376,54.3,4.5404,5.0,287.0,19.6,396.90,6.87,test_data_val,1
322,0.35114,0.0,7.38,0.0,NaN,6.041,49.9,4.7211,5.0,287.0,19.6,396.90,7.70,test_data_val,1
323,0.28392,0.0,7.38,0.0,NaN,5.708,74.3,4.7211,5.0,287.0,19.6,391.13,11.74,test_data_val,1
324,0.34109,0.0,7.38,0.0,NaN,6.415,40.1,4.7211,5.0,287.0,19.6,396.90,6.12,test_data_val,1
325,0.19186,0.0,7.38,0.0,NaN,6.431,14.7,5.4159,5.0,287.0,19.6,393.68,5.08,test_data_val,1
326,0.30347,0.0,7.38,0.0,NaN,6.312,28.9,5.4159,5.0,287.0,19.6,396.90,6.15,test_data_val,1
327,0.24103,0.0,7.38,0.0,NaN,6.083,43.7,5.4159,5.0,287.0,19.6,396.90,12.79,test_data_val,1
328,0.06617,0.0,3.24,0.0,NaN,5.868,25.8,5.2146,4.0,430.0,16.9,382.44,9.97,test_data_val,1
329,0.06724,0.0,3.24,0.0,NaN,6.333,17.2,5.2146,4.0,430.0,16.9,375.21,7.34,test_data_val,1
330,0.04544,0.0,3.24,0.0,NaN,6.144,32.2,5.8736,4.0,430.0,16.9,368.57,9.09,test_data_val,1
331,0.05023,35.0,6.06,0.0,NaN,5.706,28.4,6.6407,1.0,304.0,16.9,394.02,12.43,test_data_val,1
332,0.03466,35.0,6.06,0.0,NaN,6.031,23.3,6.6407,1.0,304.0,16.9,362.25,7.83,test_data_val,1
341,0.01301,35.0,1.52,0.0,NaN,7.241,49.3,7.0379,1.0,284.0,15.5,394.74,5.49,test_data_val,1
343,0.02543,55.0,3.78,0.0,NaN,6.696,56.4,5.7321,5.0,370.0,17.6,396.90,7.18,test_data_val,1
344,0.03049,55.0,3.78,0.0,NaN,6.874,28.1,6.4654,5.0,370.0,17.6,387.97,4.61,test_data_val,1
345,0.03113,0.0,4.39,0.0,NaN,6.014,48.5,8.0136,3.0,352.0,18.8,385.64,10.53,test_data_val,1
346,0.06162,0.0,4.39,0.0,NaN,5.898,52.3,8.0136,3.0,352.0,18.8,364.61,12.67,test_data_val,1
347,0.01870,85.0,4.15,0.0,NaN,6.516,27.7,8.5353,4.0,351.0,17.9,392.43,6.36,test_data_val,1
348,0.01501,80.0,2.01,0.0,NaN,6.635,29.7,8.3440,4.0,280.0,17.0,390.94,5.99,test_data_val,1
349,0.02899,40.0,1.25,0.0,NaN,6.939,34.5,8.7921,1.0,335.0,19.7,389.85,5.89,test_data_val,1
350,0.06211,40.0,1.25,0.0,NaN,6.490,44.4,8.7921,1.0,335.0,19.7,396.90,5.98,test_data_val,1
351,0.07950,60.0,1.69,0.0,NaN,6.579,35.9,10.7103,4.0,411.0,18.3,370.78,5.49,test_data_val,1
352,0.07244,60.0,1.69,0.0,NaN,5.884,18.5,10.7103,4.0,411.0,18.3,392.33,7.79,test_data_val,1
353,0.01709,90.0,2.02,0.0,NaN,6.728,36.1,12.1265,5.0,187.0,17.0,384.46,4.50,test_data_val,1
354,0.04301,80.0,1.91,0.0,NaN,5.663,21.9,10.5857,4.0,334.0,22.0,382.80,8.05,test_data_val,1
355,0.10659,80.0,1.91,0.0,NaN,5.936,19.5,10.5857,4.0,334.0,22.0,376.04,5.57,test_data_val,1

In [13]:
df[df["NOX"].notnull()]

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,test_data,flg
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,test_data_val,1
6,0.08829,12.5,7.87,0.0,0.524,6.012,66.6,5.5605,5.0,311.0,15.2,395.60,12.43,test_data_val,1
7,0.14455,12.5,7.87,0.0,0.524,6.172,96.1,5.9505,5.0,311.0,15.2,396.90,19.15,test_data_val,1
8,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,15.2,386.63,29.93,test_data_val,1
9,0.17004,12.5,7.87,0.0,0.524,6.004,85.9,6.5921,5.0,311.0,15.2,386.71,17.10,test_data_val,1
10,0.22489,12.5,7.87,0.0,0.524,6.377,94.3,6.3467,5.0,311.0,15.2,392.52,20.45,test_data_val,1
11,0.11747,12.5,7.87,0.0,0.524,6.009,82.9,6.2267,5.0,311.0,15.2,396.90,13.27,test_data_val,1
12,0.09378,12.5,7.87,0.0,0.524,5.889,39.0,5.4509,5.0,311.0,15.2,390.50,15.71,test_data_val,1
13,0.62976,0.0,8.14,0.0,0.538,5.949,61.8,4.7075,4.0,307.0,21.0,396.90,8.26,test_data_val,1
14,0.63796,0.0,8.14,0.0,0.538,6.096,84.5,4.4619,4.0,307.0,21.0,380.02,10.26,test_data_val,1
15,0.62739,0.0,8.14,0.0,0.538,5.834,56.5,4.4986,4.0,307.0,21.0,395.62,8.47,test_data_val,1
16,1.05393,0.0,8.14,0.0,0.538,5.935,29.3,4.4986,4.0,307.0,21.0,386.85,6.58,test_data_val,1
17,0.78420,0.0,8.14,0.0,0.538,5.990,81.7,4.2579,4.0,307.0,21.0,386.75,14.67,test_data_val,1
18,0.80271,0.0,8.14,0.0,0.538,5.456,36.6,3.7965,4.0,307.0,21.0,288.99,11.69,test_data_val,1
19,0.72580,0.0,8.14,0.0,0.538,5.727,69.5,3.7965,4.0,307.0,21.0,390.95,11.28,test_data_val,1
20,1.25179,0.0,8.14,0.0,0.538,5.570,98.1,3.7979,4.0,307.0,21.0,376.57,21.02,test_data_val,1
21,0.85204,0.0,8.14,0.0,0.538,5.965,89.2,4.0123,4.0,307.0,21.0,392.53,13.83,test_data_val,1
22,1.23247,0.0,8.14,0.0,0.538,6.142,91.7,3.9769,4.0,307.0,21.0,396.90,18.72,test_data_val,1
23,0.98843,0.0,8.14,0.0,0.538,5.813,100.0,4.0952,4.0,307.0,21.0,394.54,19.88,test_data_val,1
24,0.75026,0.0,8.14,0.0,0.538,5.924,94.1,4.3996,4.0,307.0,21.0,394.33,16.30,test_data_val,1
25,0.84054,0.0,8.14,0.0,0.538,5.599,85.7,4.4546,4.0,307.0,21.0,303.42,16.51,test_data_val,1
26,0.67191,0.0,8.14,0.0,0.538,5.813,90.3,4.6820,4.0,307.0,21.0,376.88,14.81,test_data_val,1
27,0.95577,0.0,8.14,0.0,0.538,6.047,88.8,4.4534,4.0,307.0,21.0,306.38,17.28,test_data_val,1
28,0.77299,0.0,8.14,0.0,0.538,6.495,94.4,4.4547,4.0,307.0,21.0,387.94,12.80,test_data_val,1
29,1.00245,0.0,8.14,0.0,0.538,6.674,87.3,4.2390,4.0,307.0,21.0,380.23,11.98,test_data_val,1
30,1.13081,0.0,8.14,0.0,0.538,5.713,94.1,4.2330,4.0,307.0,21.0,360.17,22.60,test_data_val,1
31,1.35472,0.0,8.14,0.0,0.538,6.072,100.0,4.1750,4.0,307.0,21.0,376.73,13.04,test_data_val,1
32,1.38799,0.0,8.14,0.0,0.538,5.950,82.0,3.9900,4.0,307.0,21.0,232.60,27.71,test_data_val,1
33,1.15172,0.0,8.14,0.0,0.538,5.701,95.0,3.7872,4.0,307.0,21.0,358.77,18.35,test_data_val,1
34,1.61282,0.0,8.14,0.0,0.538,6.096,96.9,3.7598,4.0,307.0,21.0,248.31,20.34,test_data_val,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,4.87141,0.0,18.10,0.0,0.614,6.484,93.6,2.3053,24.0,666.0,20.2,396.21,18.68,test_data_val,1
477,15.02340,0.0,18.10,0.0,0.614,5.304,97.3,2.1007,24.0,666.0,20.2,349.48,24.91,test_data_val,1
478,10.23300,0.0,18.10,0.0,0.614,6.185,96.7,2.1705,24.0,666.0,20.2,379.70,18.03,test_data_val,1
479,14.33370,0.0,18.10,0.0,0.614,6.229,88.0,1.9512,24.0,666.0,20.2,383.32,13.11,test_data_val,1
480,5.82401,0.0,18.10,0.0,0.532,6.242,64.7,3.4242,24.0,666.0,20.2,396.90,10.74,test_data_val,1
481,5.70818,0.0,18.10,0.0,0.532,6.750,74.9,3.3317,24.0,666.0,20.2,393.07,7.74,test_data_val,1
482,5.73116,0.0,18.10,0.0,0.532,7.061,77.0,3.4106,24.0,666.0,20.2,395.28,7.01,test_data_val,1
483,2.81838,0.0,18.10,0.0,0.532,5.762,40.3,4.0983,24.0,666.0,20.2,392.92,10.42,test_data_val,1
484,2.37857,0.0,18.10,0.0,0.583,5.871,41.9,3.7240,24.0,666.0,20.2,370.73,13.34,test_data_val,1
485,3.67367,0.0,18.10,0.0,0.583,6.312,51.9,3.9917,24.0,666.0,20.2,388.62,10.58,test_data_val,1
486,5.69175,0.0,18.10,0.0,0.583,6.114,79.8,3.5459,24.0,666.0,20.2,392.68,14.98,test_data_val,1
487,4.83567,0.0,18.10,0.0,0.583,5.905,53.2,3.1523,24.0,666.0,20.2,388.22,11.45,test_data_val,1
488,0.15086,0.0,27.74,0.0,0.609,5.454,92.7,1.8209,4.0,711.0,20.1,395.09,18.06,test_data_val,1
489,0.18337,0.0,27.74,0.0,0.609,5.414,98.3,1.7554,4.0,711.0,20.1,344.05,23.97,test_data_val,1
490,0.20746,0.0,27.74,0.0,0.609,5.093,98.0,1.8226,4.0,711.0,20.1,318.43,29.68,test_data_val,1
491,0.10574,0.0,27.74,0.0,0.609,5.983,98.8,1.8681,4.0,711.0,20.1,390.11,18.07,test_data_val,1
492,0.11132,0.0,27.74,0.0,0.609,5.983,83.5,2.1099,4.0,711.0,20.1,396.90,13.35,test_data_val,1
493,0.17331,0.0,9.69,0.0,0.585,5.707,54.0,2.3817,6.0,391.0,19.2,396.90,12.01,test_data_val,1
494,0.27957,0.0,9.69,0.0,0.585,5.926,42.6,2.3817,6.0,391.0,19.2,396.90,13.59,test_data_val,1
495,0.17899,0.0,9.69,0.0,0.585,5.670,28.8,2.7986,6.0,391.0,19.2,393.29,17.60,test_data_val,1
496,0.28960,0.0,9.69,0.0,0.585,5.390,72.9,2.7986,6.0,391.0,19.2,396.90,21.14,test_data_val,1
497,0.26838,0.0,9.69,0.0,0.585,5.794,70.6,2.8927,6.0,391.0,19.2,396.90,14.10,test_data_val,1
498,0.23912,0.0,9.69,0.0,0.585,6.019,65.3,2.4091,6.0,391.0,19.2,396.90,12.92,test_data_val,1
499,0.17783,0.0,9.69,0.0,0.585,5.569,73.5,2.3999,6.0,391.0,19.2,395.77,15.10,test_data_val,1
500,0.22438,0.0,9.69,0.0,0.585,6.027,79.7,2.4982,6.0,391.0,19.2,396.90,14.33,test_data_val,1
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67,test_data_val,1
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,test_data_val,1
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,test_data_val,1
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,test_data_val,1
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88,test_data_val,1

In [14]:
df[["RM", "AGE"]].query('RM >= 6 and RM <= 8')

        RM    AGE
0    6.575   65.2
1    6.421   78.9
2    7.185   61.1
3    6.998   45.8
4    7.147   54.2
5    6.430   58.7
6    6.012   66.6
7    6.172   96.1
9    6.004   85.9
10   6.377   94.3
11   6.009   82.9
14   6.096   84.5
22   6.142   91.7
27   6.047   88.8
28   6.495   94.4
29   6.674   87.3
31   6.072  100.0
34   6.096   96.9
39   6.595   21.8
40   7.024   15.8
41   6.770    2.9
42   6.169    6.6
43   6.211    6.5
44   6.069   40.0
47   6.030   85.5
51   6.115   63.0
52   6.511   21.1
55   7.249   21.9
56   6.383   35.7
57   6.816   40.5
..     ...    ...
454  6.728   94.1
455  6.525   86.5
458  6.301   83.7
459  6.081   84.4
460  6.701   90.0
461  6.376   88.4
462  6.317   83.0
463  6.513   89.9
464  6.209   65.4
467  6.003   94.5
470  6.167   84.0
471  6.229   90.7
472  6.437   75.0
473  6.980   67.6
475  6.162   97.4
476  6.484   93.6
478  6.185   96.7
479  6.229   88.0
480  6.242   64.7
481  6.750   74.9
482  7.061   77.0
485  6.312   51.9
486  6.114   79.8
498  6.019   65.3
500  6.027   79.7
501  6.593   69.1
502  6.120   76.7
503  6.976   91.0
504  6.794   89.3
505  6.030   80.8

[320 rows x 2 columns]

In [15]:
df[df["test_data"].str.startswith('te')]

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,test_data,flg
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,test_data_val,1
1,0.02731,0.0,7.07,0.0,NaN,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,test_data_val,1
2,0.02729,0.0,7.07,0.0,NaN,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,test_data_val,1
3,0.03237,0.0,2.18,0.0,NaN,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,test_data_val,1
4,0.06905,0.0,2.18,0.0,NaN,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,test_data_val,1
5,0.02985,0.0,2.18,0.0,NaN,6.430,58.7,6.0622,3.0,222.0,18.7,394.12,5.21,test_data_val,1
6,0.08829,12.5,7.87,0.0,0.524,6.012,66.6,5.5605,5.0,311.0,15.2,395.60,12.43,test_data_val,1
7,0.14455,12.5,7.87,0.0,0.524,6.172,96.1,5.9505,5.0,311.0,15.2,396.90,19.15,test_data_val,1
8,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,15.2,386.63,29.93,test_data_val,1
9,0.17004,12.5,7.87,0.0,0.524,6.004,85.9,6.5921,5.0,311.0,15.2,386.71,17.10,test_data_val,1
10,0.22489,12.5,7.87,0.0,0.524,6.377,94.3,6.3467,5.0,311.0,15.2,392.52,20.45,test_data_val,1
11,0.11747,12.5,7.87,0.0,0.524,6.009,82.9,6.2267,5.0,311.0,15.2,396.90,13.27,test_data_val,1
12,0.09378,12.5,7.87,0.0,0.524,5.889,39.0,5.4509,5.0,311.0,15.2,390.50,15.71,test_data_val,1
13,0.62976,0.0,8.14,0.0,0.538,5.949,61.8,4.7075,4.0,307.0,21.0,396.90,8.26,test_data_val,1
14,0.63796,0.0,8.14,0.0,0.538,6.096,84.5,4.4619,4.0,307.0,21.0,380.02,10.26,test_data_val,1
15,0.62739,0.0,8.14,0.0,0.538,5.834,56.5,4.4986,4.0,307.0,21.0,395.62,8.47,test_data_val,1
16,1.05393,0.0,8.14,0.0,0.538,5.935,29.3,4.4986,4.0,307.0,21.0,386.85,6.58,test_data_val,1
17,0.78420,0.0,8.14,0.0,0.538,5.990,81.7,4.2579,4.0,307.0,21.0,386.75,14.67,test_data_val,1
18,0.80271,0.0,8.14,0.0,0.538,5.456,36.6,3.7965,4.0,307.0,21.0,288.99,11.69,test_data_val,1
19,0.72580,0.0,8.14,0.0,0.538,5.727,69.5,3.7965,4.0,307.0,21.0,390.95,11.28,test_data_val,1
20,1.25179,0.0,8.14,0.0,0.538,5.570,98.1,3.7979,4.0,307.0,21.0,376.57,21.02,test_data_val,1
21,0.85204,0.0,8.14,0.0,0.538,5.965,89.2,4.0123,4.0,307.0,21.0,392.53,13.83,test_data_val,1
22,1.23247,0.0,8.14,0.0,0.538,6.142,91.7,3.9769,4.0,307.0,21.0,396.90,18.72,test_data_val,1
23,0.98843,0.0,8.14,0.0,0.538,5.813,100.0,4.0952,4.0,307.0,21.0,394.54,19.88,test_data_val,1
24,0.75026,0.0,8.14,0.0,0.538,5.924,94.1,4.3996,4.0,307.0,21.0,394.33,16.30,test_data_val,1
25,0.84054,0.0,8.14,0.0,0.538,5.599,85.7,4.4546,4.0,307.0,21.0,303.42,16.51,test_data_val,1
26,0.67191,0.0,8.14,0.0,0.538,5.813,90.3,4.6820,4.0,307.0,21.0,376.88,14.81,test_data_val,1
27,0.95577,0.0,8.14,0.0,0.538,6.047,88.8,4.4534,4.0,307.0,21.0,306.38,17.28,test_data_val,1
28,0.77299,0.0,8.14,0.0,0.538,6.495,94.4,4.4547,4.0,307.0,21.0,387.94,12.80,test_data_val,1
29,1.00245,0.0,8.14,0.0,0.538,6.674,87.3,4.2390,4.0,307.0,21.0,380.23,11.98,test_data_val,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,4.87141,0.0,18.10,0.0,0.614,6.484,93.6,2.3053,24.0,666.0,20.2,396.21,18.68,test_data_val,1
477,15.02340,0.0,18.10,0.0,0.614,5.304,97.3,2.1007,24.0,666.0,20.2,349.48,24.91,test_data_val,1
478,10.23300,0.0,18.10,0.0,0.614,6.185,96.7,2.1705,24.0,666.0,20.2,379.70,18.03,test_data_val,1
479,14.33370,0.0,18.10,0.0,0.614,6.229,88.0,1.9512,24.0,666.0,20.2,383.32,13.11,test_data_val,1
480,5.82401,0.0,18.10,0.0,0.532,6.242,64.7,3.4242,24.0,666.0,20.2,396.90,10.74,test_data_val,1
481,5.70818,0.0,18.10,0.0,0.532,6.750,74.9,3.3317,24.0,666.0,20.2,393.07,7.74,test_data_val,1
482,5.73116,0.0,18.10,0.0,0.532,7.061,77.0,3.4106,24.0,666.0,20.2,395.28,7.01,test_data_val,1
483,2.81838,0.0,18.10,0.0,0.532,5.762,40.3,4.0983,24.0,666.0,20.2,392.92,10.42,test_data_val,1
484,2.37857,0.0,18.10,0.0,0.583,5.871,41.9,3.7240,24.0,666.0,20.2,370.73,13.34,test_data_val,1
485,3.67367,0.0,18.10,0.0,0.583,6.312,51.9,3.9917,24.0,666.0,20.2,388.62,10.58,test_data_val,1
486,5.69175,0.0,18.10,0.0,0.583,6.114,79.8,3.5459,24.0,666.0,20.2,392.68,14.98,test_data_val,1
487,4.83567,0.0,18.10,0.0,0.583,5.905,53.2,3.1523,24.0,666.0,20.2,388.22,11.45,test_data_val,1
488,0.15086,0.0,27.74,0.0,0.609,5.454,92.7,1.8209,4.0,711.0,20.1,395.09,18.06,test_data_val,1
489,0.18337,0.0,27.74,0.0,0.609,5.414,98.3,1.7554,4.0,711.0,20.1,344.05,23.97,test_data_val,1
490,0.20746,0.0,27.74,0.0,0.609,5.093,98.0,1.8226,4.0,711.0,20.1,318.43,29.68,test_data_val,1
491,0.10574,0.0,27.74,0.0,0.609,5.983,98.8,1.8681,4.0,711.0,20.1,390.11,18.07,test_data_val,1
492,0.11132,0.0,27.74,0.0,0.609,5.983,83.5,2.1099,4.0,711.0,20.1,396.90,13.35,test_data_val,1
493,0.17331,0.0,9.69,0.0,0.585,5.707,54.0,2.3817,6.0,391.0,19.2,396.90,12.01,test_data_val,1
494,0.27957,0.0,9.69,0.0,0.585,5.926,42.6,2.3817,6.0,391.0,19.2,396.90,13.59,test_data_val,1
495,0.17899,0.0,9.69,0.0,0.585,5.670,28.8,2.7986,6.0,391.0,19.2,393.29,17.60,test_data_val,1
496,0.28960,0.0,9.69,0.0,0.585,5.390,72.9,2.7986,6.0,391.0,19.2,396.90,21.14,test_data_val,1
497,0.26838,0.0,9.69,0.0,0.585,5.794,70.6,2.8927,6.0,391.0,19.2,396.90,14.10,test_data_val,1
498,0.23912,0.0,9.69,0.0,0.585,6.019,65.3,2.4091,6.0,391.0,19.2,396.90,12.92,test_data_val,1
499,0.17783,0.0,9.69,0.0,0.585,5.569,73.5,2.3999,6.0,391.0,19.2,395.77,15.10,test_data_val,1
500,0.22438,0.0,9.69,0.0,0.585,6.027,79.7,2.4982,6.0,391.0,19.2,396.90,14.33,test_data_val,1
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67,test_data_val,1
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,test_data_val,1
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,test_data_val,1
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,test_data_val,1
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88,test_data_val,1

In [16]:
df[df["test_data"].str.contains('[ぁ-んァ-ン一-龥a-z]t_d[ぁ-んァ-ン一-龥a-z]', regex=True)]

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,test_data,flg
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,test_data_val,1
1,0.02731,0.0,7.07,0.0,NaN,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,test_data_val,1
2,0.02729,0.0,7.07,0.0,NaN,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,test_data_val,1
3,0.03237,0.0,2.18,0.0,NaN,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,test_data_val,1
4,0.06905,0.0,2.18,0.0,NaN,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,test_data_val,1
5,0.02985,0.0,2.18,0.0,NaN,6.430,58.7,6.0622,3.0,222.0,18.7,394.12,5.21,test_data_val,1
6,0.08829,12.5,7.87,0.0,0.524,6.012,66.6,5.5605,5.0,311.0,15.2,395.60,12.43,test_data_val,1
7,0.14455,12.5,7.87,0.0,0.524,6.172,96.1,5.9505,5.0,311.0,15.2,396.90,19.15,test_data_val,1
8,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,15.2,386.63,29.93,test_data_val,1
9,0.17004,12.5,7.87,0.0,0.524,6.004,85.9,6.5921,5.0,311.0,15.2,386.71,17.10,test_data_val,1
10,0.22489,12.5,7.87,0.0,0.524,6.377,94.3,6.3467,5.0,311.0,15.2,392.52,20.45,test_data_val,1
11,0.11747,12.5,7.87,0.0,0.524,6.009,82.9,6.2267,5.0,311.0,15.2,396.90,13.27,test_data_val,1
12,0.09378,12.5,7.87,0.0,0.524,5.889,39.0,5.4509,5.0,311.0,15.2,390.50,15.71,test_data_val,1
13,0.62976,0.0,8.14,0.0,0.538,5.949,61.8,4.7075,4.0,307.0,21.0,396.90,8.26,test_data_val,1
14,0.63796,0.0,8.14,0.0,0.538,6.096,84.5,4.4619,4.0,307.0,21.0,380.02,10.26,test_data_val,1
15,0.62739,0.0,8.14,0.0,0.538,5.834,56.5,4.4986,4.0,307.0,21.0,395.62,8.47,test_data_val,1
16,1.05393,0.0,8.14,0.0,0.538,5.935,29.3,4.4986,4.0,307.0,21.0,386.85,6.58,test_data_val,1
17,0.78420,0.0,8.14,0.0,0.538,5.990,81.7,4.2579,4.0,307.0,21.0,386.75,14.67,test_data_val,1
18,0.80271,0.0,8.14,0.0,0.538,5.456,36.6,3.7965,4.0,307.0,21.0,288.99,11.69,test_data_val,1
19,0.72580,0.0,8.14,0.0,0.538,5.727,69.5,3.7965,4.0,307.0,21.0,390.95,11.28,test_data_val,1
20,1.25179,0.0,8.14,0.0,0.538,5.570,98.1,3.7979,4.0,307.0,21.0,376.57,21.02,test_data_val,1
21,0.85204,0.0,8.14,0.0,0.538,5.965,89.2,4.0123,4.0,307.0,21.0,392.53,13.83,test_data_val,1
22,1.23247,0.0,8.14,0.0,0.538,6.142,91.7,3.9769,4.0,307.0,21.0,396.90,18.72,test_data_val,1
23,0.98843,0.0,8.14,0.0,0.538,5.813,100.0,4.0952,4.0,307.0,21.0,394.54,19.88,test_data_val,1
24,0.75026,0.0,8.14,0.0,0.538,5.924,94.1,4.3996,4.0,307.0,21.0,394.33,16.30,test_data_val,1
25,0.84054,0.0,8.14,0.0,0.538,5.599,85.7,4.4546,4.0,307.0,21.0,303.42,16.51,test_data_val,1
26,0.67191,0.0,8.14,0.0,0.538,5.813,90.3,4.6820,4.0,307.0,21.0,376.88,14.81,test_data_val,1
27,0.95577,0.0,8.14,0.0,0.538,6.047,88.8,4.4534,4.0,307.0,21.0,306.38,17.28,test_data_val,1
28,0.77299,0.0,8.14,0.0,0.538,6.495,94.4,4.4547,4.0,307.0,21.0,387.94,12.80,test_data_val,1
29,1.00245,0.0,8.14,0.0,0.538,6.674,87.3,4.2390,4.0,307.0,21.0,380.23,11.98,test_data_val,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,4.87141,0.0,18.10,0.0,0.614,6.484,93.6,2.3053,24.0,666.0,20.2,396.21,18.68,test_data_val,1
477,15.02340,0.0,18.10,0.0,0.614,5.304,97.3,2.1007,24.0,666.0,20.2,349.48,24.91,test_data_val,1
478,10.23300,0.0,18.10,0.0,0.614,6.185,96.7,2.1705,24.0,666.0,20.2,379.70,18.03,test_data_val,1
479,14.33370,0.0,18.10,0.0,0.614,6.229,88.0,1.9512,24.0,666.0,20.2,383.32,13.11,test_data_val,1
480,5.82401,0.0,18.10,0.0,0.532,6.242,64.7,3.4242,24.0,666.0,20.2,396.90,10.74,test_data_val,1
481,5.70818,0.0,18.10,0.0,0.532,6.750,74.9,3.3317,24.0,666.0,20.2,393.07,7.74,test_data_val,1
482,5.73116,0.0,18.10,0.0,0.532,7.061,77.0,3.4106,24.0,666.0,20.2,395.28,7.01,test_data_val,1
483,2.81838,0.0,18.10,0.0,0.532,5.762,40.3,4.0983,24.0,666.0,20.2,392.92,10.42,test_data_val,1
484,2.37857,0.0,18.10,0.0,0.583,5.871,41.9,3.7240,24.0,666.0,20.2,370.73,13.34,test_data_val,1
485,3.67367,0.0,18.10,0.0,0.583,6.312,51.9,3.9917,24.0,666.0,20.2,388.62,10.58,test_data_val,1
486,5.69175,0.0,18.10,0.0,0.583,6.114,79.8,3.5459,24.0,666.0,20.2,392.68,14.98,test_data_val,1
487,4.83567,0.0,18.10,0.0,0.583,5.905,53.2,3.1523,24.0,666.0,20.2,388.22,11.45,test_data_val,1
488,0.15086,0.0,27.74,0.0,0.609,5.454,92.7,1.8209,4.0,711.0,20.1,395.09,18.06,test_data_val,1
489,0.18337,0.0,27.74,0.0,0.609,5.414,98.3,1.7554,4.0,711.0,20.1,344.05,23.97,test_data_val,1
490,0.20746,0.0,27.74,0.0,0.609,5.093,98.0,1.8226,4.0,711.0,20.1,318.43,29.68,test_data_val,1
491,0.10574,0.0,27.74,0.0,0.609,5.983,98.8,1.8681,4.0,711.0,20.1,390.11,18.07,test_data_val,1
492,0.11132,0.0,27.74,0.0,0.609,5.983,83.5,2.1099,4.0,711.0,20.1,396.90,13.35,test_data_val,1
493,0.17331,0.0,9.69,0.0,0.585,5.707,54.0,2.3817,6.0,391.0,19.2,396.90,12.01,test_data_val,1
494,0.27957,0.0,9.69,0.0,0.585,5.926,42.6,2.3817,6.0,391.0,19.2,396.90,13.59,test_data_val,1
495,0.17899,0.0,9.69,0.0,0.585,5.670,28.8,2.7986,6.0,391.0,19.2,393.29,17.60,test_data_val,1
496,0.28960,0.0,9.69,0.0,0.585,5.390,72.9,2.7986,6.0,391.0,19.2,396.90,21.14,test_data_val,1
497,0.26838,0.0,9.69,0.0,0.585,5.794,70.6,2.8927,6.0,391.0,19.2,396.90,14.10,test_data_val,1
498,0.23912,0.0,9.69,0.0,0.585,6.019,65.3,2.4091,6.0,391.0,19.2,396.90,12.92,test_data_val,1
499,0.17783,0.0,9.69,0.0,0.585,5.569,73.5,2.3999,6.0,391.0,19.2,395.77,15.10,test_data_val,1
500,0.22438,0.0,9.69,0.0,0.585,6.027,79.7,2.4982,6.0,391.0,19.2,396.90,14.33,test_data_val,1
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67,test_data_val,1
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,test_data_val,1
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,test_data_val,1
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,test_data_val,1
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88,test_data_val,1

In [17]:
df[df["test_data"].str.endswith('al')]

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,test_data,flg
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,test_data_val,1
1,0.02731,0.0,7.07,0.0,NaN,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,test_data_val,1
2,0.02729,0.0,7.07,0.0,NaN,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,test_data_val,1
3,0.03237,0.0,2.18,0.0,NaN,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,test_data_val,1
4,0.06905,0.0,2.18,0.0,NaN,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,test_data_val,1
5,0.02985,0.0,2.18,0.0,NaN,6.430,58.7,6.0622,3.0,222.0,18.7,394.12,5.21,test_data_val,1
6,0.08829,12.5,7.87,0.0,0.524,6.012,66.6,5.5605,5.0,311.0,15.2,395.60,12.43,test_data_val,1
7,0.14455,12.5,7.87,0.0,0.524,6.172,96.1,5.9505,5.0,311.0,15.2,396.90,19.15,test_data_val,1
8,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,15.2,386.63,29.93,test_data_val,1
9,0.17004,12.5,7.87,0.0,0.524,6.004,85.9,6.5921,5.0,311.0,15.2,386.71,17.10,test_data_val,1
10,0.22489,12.5,7.87,0.0,0.524,6.377,94.3,6.3467,5.0,311.0,15.2,392.52,20.45,test_data_val,1
11,0.11747,12.5,7.87,0.0,0.524,6.009,82.9,6.2267,5.0,311.0,15.2,396.90,13.27,test_data_val,1
12,0.09378,12.5,7.87,0.0,0.524,5.889,39.0,5.4509,5.0,311.0,15.2,390.50,15.71,test_data_val,1
13,0.62976,0.0,8.14,0.0,0.538,5.949,61.8,4.7075,4.0,307.0,21.0,396.90,8.26,test_data_val,1
14,0.63796,0.0,8.14,0.0,0.538,6.096,84.5,4.4619,4.0,307.0,21.0,380.02,10.26,test_data_val,1
15,0.62739,0.0,8.14,0.0,0.538,5.834,56.5,4.4986,4.0,307.0,21.0,395.62,8.47,test_data_val,1
16,1.05393,0.0,8.14,0.0,0.538,5.935,29.3,4.4986,4.0,307.0,21.0,386.85,6.58,test_data_val,1
17,0.78420,0.0,8.14,0.0,0.538,5.990,81.7,4.2579,4.0,307.0,21.0,386.75,14.67,test_data_val,1
18,0.80271,0.0,8.14,0.0,0.538,5.456,36.6,3.7965,4.0,307.0,21.0,288.99,11.69,test_data_val,1
19,0.72580,0.0,8.14,0.0,0.538,5.727,69.5,3.7965,4.0,307.0,21.0,390.95,11.28,test_data_val,1
20,1.25179,0.0,8.14,0.0,0.538,5.570,98.1,3.7979,4.0,307.0,21.0,376.57,21.02,test_data_val,1
21,0.85204,0.0,8.14,0.0,0.538,5.965,89.2,4.0123,4.0,307.0,21.0,392.53,13.83,test_data_val,1
22,1.23247,0.0,8.14,0.0,0.538,6.142,91.7,3.9769,4.0,307.0,21.0,396.90,18.72,test_data_val,1
23,0.98843,0.0,8.14,0.0,0.538,5.813,100.0,4.0952,4.0,307.0,21.0,394.54,19.88,test_data_val,1
24,0.75026,0.0,8.14,0.0,0.538,5.924,94.1,4.3996,4.0,307.0,21.0,394.33,16.30,test_data_val,1
25,0.84054,0.0,8.14,0.0,0.538,5.599,85.7,4.4546,4.0,307.0,21.0,303.42,16.51,test_data_val,1
26,0.67191,0.0,8.14,0.0,0.538,5.813,90.3,4.6820,4.0,307.0,21.0,376.88,14.81,test_data_val,1
27,0.95577,0.0,8.14,0.0,0.538,6.047,88.8,4.4534,4.0,307.0,21.0,306.38,17.28,test_data_val,1
28,0.77299,0.0,8.14,0.0,0.538,6.495,94.4,4.4547,4.0,307.0,21.0,387.94,12.80,test_data_val,1
29,1.00245,0.0,8.14,0.0,0.538,6.674,87.3,4.2390,4.0,307.0,21.0,380.23,11.98,test_data_val,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,4.87141,0.0,18.10,0.0,0.614,6.484,93.6,2.3053,24.0,666.0,20.2,396.21,18.68,test_data_val,1
477,15.02340,0.0,18.10,0.0,0.614,5.304,97.3,2.1007,24.0,666.0,20.2,349.48,24.91,test_data_val,1
478,10.23300,0.0,18.10,0.0,0.614,6.185,96.7,2.1705,24.0,666.0,20.2,379.70,18.03,test_data_val,1
479,14.33370,0.0,18.10,0.0,0.614,6.229,88.0,1.9512,24.0,666.0,20.2,383.32,13.11,test_data_val,1
480,5.82401,0.0,18.10,0.0,0.532,6.242,64.7,3.4242,24.0,666.0,20.2,396.90,10.74,test_data_val,1
481,5.70818,0.0,18.10,0.0,0.532,6.750,74.9,3.3317,24.0,666.0,20.2,393.07,7.74,test_data_val,1
482,5.73116,0.0,18.10,0.0,0.532,7.061,77.0,3.4106,24.0,666.0,20.2,395.28,7.01,test_data_val,1
483,2.81838,0.0,18.10,0.0,0.532,5.762,40.3,4.0983,24.0,666.0,20.2,392.92,10.42,test_data_val,1
484,2.37857,0.0,18.10,0.0,0.583,5.871,41.9,3.7240,24.0,666.0,20.2,370.73,13.34,test_data_val,1
485,3.67367,0.0,18.10,0.0,0.583,6.312,51.9,3.9917,24.0,666.0,20.2,388.62,10.58,test_data_val,1
486,5.69175,0.0,18.10,0.0,0.583,6.114,79.8,3.5459,24.0,666.0,20.2,392.68,14.98,test_data_val,1
487,4.83567,0.0,18.10,0.0,0.583,5.905,53.2,3.1523,24.0,666.0,20.2,388.22,11.45,test_data_val,1
488,0.15086,0.0,27.74,0.0,0.609,5.454,92.7,1.8209,4.0,711.0,20.1,395.09,18.06,test_data_val,1
489,0.18337,0.0,27.74,0.0,0.609,5.414,98.3,1.7554,4.0,711.0,20.1,344.05,23.97,test_data_val,1
490,0.20746,0.0,27.74,0.0,0.609,5.093,98.0,1.8226,4.0,711.0,20.1,318.43,29.68,test_data_val,1
491,0.10574,0.0,27.74,0.0,0.609,5.983,98.8,1.8681,4.0,711.0,20.1,390.11,18.07,test_data_val,1
492,0.11132,0.0,27.74,0.0,0.609,5.983,83.5,2.1099,4.0,711.0,20.1,396.90,13.35,test_data_val,1
493,0.17331,0.0,9.69,0.0,0.585,5.707,54.0,2.3817,6.0,391.0,19.2,396.90,12.01,test_data_val,1
494,0.27957,0.0,9.69,0.0,0.585,5.926,42.6,2.3817,6.0,391.0,19.2,396.90,13.59,test_data_val,1
495,0.17899,0.0,9.69,0.0,0.585,5.670,28.8,2.7986,6.0,391.0,19.2,393.29,17.60,test_data_val,1
496,0.28960,0.0,9.69,0.0,0.585,5.390,72.9,2.7986,6.0,391.0,19.2,396.90,21.14,test_data_val,1
497,0.26838,0.0,9.69,0.0,0.585,5.794,70.6,2.8927,6.0,391.0,19.2,396.90,14.10,test_data_val,1
498,0.23912,0.0,9.69,0.0,0.585,6.019,65.3,2.4091,6.0,391.0,19.2,396.90,12.92,test_data_val,1
499,0.17783,0.0,9.69,0.0,0.585,5.569,73.5,2.3999,6.0,391.0,19.2,395.77,15.10,test_data_val,1
500,0.22438,0.0,9.69,0.0,0.585,6.027,79.7,2.4982,6.0,391.0,19.2,396.90,14.33,test_data_val,1
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67,test_data_val,1
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,test_data_val,1
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,test_data_val,1
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,test_data_val,1
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88,test_data_val,1

In [18]:
df.loc[df.NOX < 0.5, "NOX"]=None
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,test_data,flg
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,test_data_val,1
1,0.02731,0.0,7.07,0.0,NaN,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,test_data_val,1
2,0.02729,0.0,7.07,0.0,NaN,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,test_data_val,1
3,0.03237,0.0,2.18,0.0,NaN,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,test_data_val,1
4,0.06905,0.0,2.18,0.0,NaN,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,test_data_val,1
5,0.02985,0.0,2.18,0.0,NaN,6.430,58.7,6.0622,3.0,222.0,18.7,394.12,5.21,test_data_val,1
6,0.08829,12.5,7.87,0.0,0.524,6.012,66.6,5.5605,5.0,311.0,15.2,395.60,12.43,test_data_val,1
7,0.14455,12.5,7.87,0.0,0.524,6.172,96.1,5.9505,5.0,311.0,15.2,396.90,19.15,test_data_val,1
8,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,15.2,386.63,29.93,test_data_val,1
9,0.17004,12.5,7.87,0.0,0.524,6.004,85.9,6.5921,5.0,311.0,15.2,386.71,17.10,test_data_val,1
10,0.22489,12.5,7.87,0.0,0.524,6.377,94.3,6.3467,5.0,311.0,15.2,392.52,20.45,test_data_val,1
11,0.11747,12.5,7.87,0.0,0.524,6.009,82.9,6.2267,5.0,311.0,15.2,396.90,13.27,test_data_val,1
12,0.09378,12.5,7.87,0.0,0.524,5.889,39.0,5.4509,5.0,311.0,15.2,390.50,15.71,test_data_val,1
13,0.62976,0.0,8.14,0.0,0.538,5.949,61.8,4.7075,4.0,307.0,21.0,396.90,8.26,test_data_val,1
14,0.63796,0.0,8.14,0.0,0.538,6.096,84.5,4.4619,4.0,307.0,21.0,380.02,10.26,test_data_val,1
15,0.62739,0.0,8.14,0.0,0.538,5.834,56.5,4.4986,4.0,307.0,21.0,395.62,8.47,test_data_val,1
16,1.05393,0.0,8.14,0.0,0.538,5.935,29.3,4.4986,4.0,307.0,21.0,386.85,6.58,test_data_val,1
17,0.78420,0.0,8.14,0.0,0.538,5.990,81.7,4.2579,4.0,307.0,21.0,386.75,14.67,test_data_val,1
18,0.80271,0.0,8.14,0.0,0.538,5.456,36.6,3.7965,4.0,307.0,21.0,288.99,11.69,test_data_val,1
19,0.72580,0.0,8.14,0.0,0.538,5.727,69.5,3.7965,4.0,307.0,21.0,390.95,11.28,test_data_val,1
20,1.25179,0.0,8.14,0.0,0.538,5.570,98.1,3.7979,4.0,307.0,21.0,376.57,21.02,test_data_val,1
21,0.85204,0.0,8.14,0.0,0.538,5.965,89.2,4.0123,4.0,307.0,21.0,392.53,13.83,test_data_val,1
22,1.23247,0.0,8.14,0.0,0.538,6.142,91.7,3.9769,4.0,307.0,21.0,396.90,18.72,test_data_val,1
23,0.98843,0.0,8.14,0.0,0.538,5.813,100.0,4.0952,4.0,307.0,21.0,394.54,19.88,test_data_val,1
24,0.75026,0.0,8.14,0.0,0.538,5.924,94.1,4.3996,4.0,307.0,21.0,394.33,16.30,test_data_val,1
25,0.84054,0.0,8.14,0.0,0.538,5.599,85.7,4.4546,4.0,307.0,21.0,303.42,16.51,test_data_val,1
26,0.67191,0.0,8.14,0.0,0.538,5.813,90.3,4.6820,4.0,307.0,21.0,376.88,14.81,test_data_val,1
27,0.95577,0.0,8.14,0.0,0.538,6.047,88.8,4.4534,4.0,307.0,21.0,306.38,17.28,test_data_val,1
28,0.77299,0.0,8.14,0.0,0.538,6.495,94.4,4.4547,4.0,307.0,21.0,387.94,12.80,test_data_val,1
29,1.00245,0.0,8.14,0.0,0.538,6.674,87.3,4.2390,4.0,307.0,21.0,380.23,11.98,test_data_val,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,4.87141,0.0,18.10,0.0,0.614,6.484,93.6,2.3053,24.0,666.0,20.2,396.21,18.68,test_data_val,1
477,15.02340,0.0,18.10,0.0,0.614,5.304,97.3,2.1007,24.0,666.0,20.2,349.48,24.91,test_data_val,1
478,10.23300,0.0,18.10,0.0,0.614,6.185,96.7,2.1705,24.0,666.0,20.2,379.70,18.03,test_data_val,1
479,14.33370,0.0,18.10,0.0,0.614,6.229,88.0,1.9512,24.0,666.0,20.2,383.32,13.11,test_data_val,1
480,5.82401,0.0,18.10,0.0,0.532,6.242,64.7,3.4242,24.0,666.0,20.2,396.90,10.74,test_data_val,1
481,5.70818,0.0,18.10,0.0,0.532,6.750,74.9,3.3317,24.0,666.0,20.2,393.07,7.74,test_data_val,1
482,5.73116,0.0,18.10,0.0,0.532,7.061,77.0,3.4106,24.0,666.0,20.2,395.28,7.01,test_data_val,1
483,2.81838,0.0,18.10,0.0,0.532,5.762,40.3,4.0983,24.0,666.0,20.2,392.92,10.42,test_data_val,1
484,2.37857,0.0,18.10,0.0,0.583,5.871,41.9,3.7240,24.0,666.0,20.2,370.73,13.34,test_data_val,1
485,3.67367,0.0,18.10,0.0,0.583,6.312,51.9,3.9917,24.0,666.0,20.2,388.62,10.58,test_data_val,1
486,5.69175,0.0,18.10,0.0,0.583,6.114,79.8,3.5459,24.0,666.0,20.2,392.68,14.98,test_data_val,1
487,4.83567,0.0,18.10,0.0,0.583,5.905,53.2,3.1523,24.0,666.0,20.2,388.22,11.45,test_data_val,1
488,0.15086,0.0,27.74,0.0,0.609,5.454,92.7,1.8209,4.0,711.0,20.1,395.09,18.06,test_data_val,1
489,0.18337,0.0,27.74,0.0,0.609,5.414,98.3,1.7554,4.0,711.0,20.1,344.05,23.97,test_data_val,1
490,0.20746,0.0,27.74,0.0,0.609,5.093,98.0,1.8226,4.0,711.0,20.1,318.43,29.68,test_data_val,1
491,0.10574,0.0,27.74,0.0,0.609,5.983,98.8,1.8681,4.0,711.0,20.1,390.11,18.07,test_data_val,1
492,0.11132,0.0,27.74,0.0,0.609,5.983,83.5,2.1099,4.0,711.0,20.1,396.90,13.35,test_data_val,1
493,0.17331,0.0,9.69,0.0,0.585,5.707,54.0,2.3817,6.0,391.0,19.2,396.90,12.01,test_data_val,1
494,0.27957,0.0,9.69,0.0,0.585,5.926,42.6,2.3817,6.0,391.0,19.2,396.90,13.59,test_data_val,1
495,0.17899,0.0,9.69,0.0,0.585,5.670,28.8,2.7986,6.0,391.0,19.2,393.29,17.60,test_data_val,1
496,0.28960,0.0,9.69,0.0,0.585,5.390,72.9,2.7986,6.0,391.0,19.2,396.90,21.14,test_data_val,1
497,0.26838,0.0,9.69,0.0,0.585,5.794,70.6,2.8927,6.0,391.0,19.2,396.90,14.10,test_data_val,1
498,0.23912,0.0,9.69,0.0,0.585,6.019,65.3,2.4091,6.0,391.0,19.2,396.90,12.92,test_data_val,1
499,0.17783,0.0,9.69,0.0,0.585,5.569,73.5,2.3999,6.0,391.0,19.2,395.77,15.10,test_data_val,1
500,0.22438,0.0,9.69,0.0,0.585,6.027,79.7,2.4982,6.0,391.0,19.2,396.90,14.33,test_data_val,1
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67,test_data_val,1
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,test_data_val,1
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,test_data_val,1
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,test_data_val,1
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88,test_data_val,1

In [19]:
df.RM.describe()

count    506.000000
mean       6.284634
std        0.702617
min        3.561000
25%        5.885500
50%        6.208500
75%        6.623500
max        8.780000
Name: RM, dtype: float64

In [20]:
df.drop(df.index[[0,2,4]],inplace=True)
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,test_data,flg
1,0.02731,0.0,7.07,0.0,NaN,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,test_data_val,1
3,0.03237,0.0,2.18,0.0,NaN,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,test_data_val,1
5,0.02985,0.0,2.18,0.0,NaN,6.430,58.7,6.0622,3.0,222.0,18.7,394.12,5.21,test_data_val,1
6,0.08829,12.5,7.87,0.0,0.524,6.012,66.6,5.5605,5.0,311.0,15.2,395.60,12.43,test_data_val,1
7,0.14455,12.5,7.87,0.0,0.524,6.172,96.1,5.9505,5.0,311.0,15.2,396.90,19.15,test_data_val,1
8,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,15.2,386.63,29.93,test_data_val,1
9,0.17004,12.5,7.87,0.0,0.524,6.004,85.9,6.5921,5.0,311.0,15.2,386.71,17.10,test_data_val,1
10,0.22489,12.5,7.87,0.0,0.524,6.377,94.3,6.3467,5.0,311.0,15.2,392.52,20.45,test_data_val,1
11,0.11747,12.5,7.87,0.0,0.524,6.009,82.9,6.2267,5.0,311.0,15.2,396.90,13.27,test_data_val,1
12,0.09378,12.5,7.87,0.0,0.524,5.889,39.0,5.4509,5.0,311.0,15.2,390.50,15.71,test_data_val,1
13,0.62976,0.0,8.14,0.0,0.538,5.949,61.8,4.7075,4.0,307.0,21.0,396.90,8.26,test_data_val,1
14,0.63796,0.0,8.14,0.0,0.538,6.096,84.5,4.4619,4.0,307.0,21.0,380.02,10.26,test_data_val,1
15,0.62739,0.0,8.14,0.0,0.538,5.834,56.5,4.4986,4.0,307.0,21.0,395.62,8.47,test_data_val,1
16,1.05393,0.0,8.14,0.0,0.538,5.935,29.3,4.4986,4.0,307.0,21.0,386.85,6.58,test_data_val,1
17,0.78420,0.0,8.14,0.0,0.538,5.990,81.7,4.2579,4.0,307.0,21.0,386.75,14.67,test_data_val,1
18,0.80271,0.0,8.14,0.0,0.538,5.456,36.6,3.7965,4.0,307.0,21.0,288.99,11.69,test_data_val,1
19,0.72580,0.0,8.14,0.0,0.538,5.727,69.5,3.7965,4.0,307.0,21.0,390.95,11.28,test_data_val,1
20,1.25179,0.0,8.14,0.0,0.538,5.570,98.1,3.7979,4.0,307.0,21.0,376.57,21.02,test_data_val,1
21,0.85204,0.0,8.14,0.0,0.538,5.965,89.2,4.0123,4.0,307.0,21.0,392.53,13.83,test_data_val,1
22,1.23247,0.0,8.14,0.0,0.538,6.142,91.7,3.9769,4.0,307.0,21.0,396.90,18.72,test_data_val,1
23,0.98843,0.0,8.14,0.0,0.538,5.813,100.0,4.0952,4.0,307.0,21.0,394.54,19.88,test_data_val,1
24,0.75026,0.0,8.14,0.0,0.538,5.924,94.1,4.3996,4.0,307.0,21.0,394.33,16.30,test_data_val,1
25,0.84054,0.0,8.14,0.0,0.538,5.599,85.7,4.4546,4.0,307.0,21.0,303.42,16.51,test_data_val,1
26,0.67191,0.0,8.14,0.0,0.538,5.813,90.3,4.6820,4.0,307.0,21.0,376.88,14.81,test_data_val,1
27,0.95577,0.0,8.14,0.0,0.538,6.047,88.8,4.4534,4.0,307.0,21.0,306.38,17.28,test_data_val,1
28,0.77299,0.0,8.14,0.0,0.538,6.495,94.4,4.4547,4.0,307.0,21.0,387.94,12.80,test_data_val,1
29,1.00245,0.0,8.14,0.0,0.538,6.674,87.3,4.2390,4.0,307.0,21.0,380.23,11.98,test_data_val,1
30,1.13081,0.0,8.14,0.0,0.538,5.713,94.1,4.2330,4.0,307.0,21.0,360.17,22.60,test_data_val,1
31,1.35472,0.0,8.14,0.0,0.538,6.072,100.0,4.1750,4.0,307.0,21.0,376.73,13.04,test_data_val,1
32,1.38799,0.0,8.14,0.0,0.538,5.950,82.0,3.9900,4.0,307.0,21.0,232.60,27.71,test_data_val,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,4.87141,0.0,18.10,0.0,0.614,6.484,93.6,2.3053,24.0,666.0,20.2,396.21,18.68,test_data_val,1
477,15.02340,0.0,18.10,0.0,0.614,5.304,97.3,2.1007,24.0,666.0,20.2,349.48,24.91,test_data_val,1
478,10.23300,0.0,18.10,0.0,0.614,6.185,96.7,2.1705,24.0,666.0,20.2,379.70,18.03,test_data_val,1
479,14.33370,0.0,18.10,0.0,0.614,6.229,88.0,1.9512,24.0,666.0,20.2,383.32,13.11,test_data_val,1
480,5.82401,0.0,18.10,0.0,0.532,6.242,64.7,3.4242,24.0,666.0,20.2,396.90,10.74,test_data_val,1
481,5.70818,0.0,18.10,0.0,0.532,6.750,74.9,3.3317,24.0,666.0,20.2,393.07,7.74,test_data_val,1
482,5.73116,0.0,18.10,0.0,0.532,7.061,77.0,3.4106,24.0,666.0,20.2,395.28,7.01,test_data_val,1
483,2.81838,0.0,18.10,0.0,0.532,5.762,40.3,4.0983,24.0,666.0,20.2,392.92,10.42,test_data_val,1
484,2.37857,0.0,18.10,0.0,0.583,5.871,41.9,3.7240,24.0,666.0,20.2,370.73,13.34,test_data_val,1
485,3.67367,0.0,18.10,0.0,0.583,6.312,51.9,3.9917,24.0,666.0,20.2,388.62,10.58,test_data_val,1
486,5.69175,0.0,18.10,0.0,0.583,6.114,79.8,3.5459,24.0,666.0,20.2,392.68,14.98,test_data_val,1
487,4.83567,0.0,18.10,0.0,0.583,5.905,53.2,3.1523,24.0,666.0,20.2,388.22,11.45,test_data_val,1
488,0.15086,0.0,27.74,0.0,0.609,5.454,92.7,1.8209,4.0,711.0,20.1,395.09,18.06,test_data_val,1
489,0.18337,0.0,27.74,0.0,0.609,5.414,98.3,1.7554,4.0,711.0,20.1,344.05,23.97,test_data_val,1
490,0.20746,0.0,27.74,0.0,0.609,5.093,98.0,1.8226,4.0,711.0,20.1,318.43,29.68,test_data_val,1
491,0.10574,0.0,27.74,0.0,0.609,5.983,98.8,1.8681,4.0,711.0,20.1,390.11,18.07,test_data_val,1
492,0.11132,0.0,27.74,0.0,0.609,5.983,83.5,2.1099,4.0,711.0,20.1,396.90,13.35,test_data_val,1
493,0.17331,0.0,9.69,0.0,0.585,5.707,54.0,2.3817,6.0,391.0,19.2,396.90,12.01,test_data_val,1
494,0.27957,0.0,9.69,0.0,0.585,5.926,42.6,2.3817,6.0,391.0,19.2,396.90,13.59,test_data_val,1
495,0.17899,0.0,9.69,0.0,0.585,5.670,28.8,2.7986,6.0,391.0,19.2,393.29,17.60,test_data_val,1
496,0.28960,0.0,9.69,0.0,0.585,5.390,72.9,2.7986,6.0,391.0,19.2,396.90,21.14,test_data_val,1
497,0.26838,0.0,9.69,0.0,0.585,5.794,70.6,2.8927,6.0,391.0,19.2,396.90,14.10,test_data_val,1
498,0.23912,0.0,9.69,0.0,0.585,6.019,65.3,2.4091,6.0,391.0,19.2,396.90,12.92,test_data_val,1
499,0.17783,0.0,9.69,0.0,0.585,5.569,73.5,2.3999,6.0,391.0,19.2,395.77,15.10,test_data_val,1
500,0.22438,0.0,9.69,0.0,0.585,6.027,79.7,2.4982,6.0,391.0,19.2,396.90,14.33,test_data_val,1
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67,test_data_val,1
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,test_data_val,1
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,test_data_val,1
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,test_data_val,1
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88,test_data_val,1

In [21]:
df.groupby("ZN").ZN.count()

ZN
0.0      370
12.5      10
17.5       1
20.0      21
21.0       4
22.0      10
25.0      10
28.0       3
30.0       6
33.0       4
34.0       3
35.0       3
40.0       7
45.0       6
52.5       3
55.0       3
60.0       4
70.0       3
75.0       3
80.0      15
82.5       2
85.0       2
90.0       5
95.0       4
100.0      1
Name: ZN, dtype: int64

In [22]:
df["RM"].sort_values(ascending=True)

365    3.561
367    3.863
374    4.138
406    4.138
384    4.368
414    4.519
412    4.628
386    4.652
388    4.880
144    4.903
373    4.906
147    4.926
366    4.963
368    4.970
310    4.973
387    5.000
152    5.012
141    5.019
392    5.036
490    5.093
413    5.155
148    5.186
156    5.272
385    5.277
477    5.304
417    5.304
209    5.344
403    5.349
362    5.362
389    5.390
       ...
256    7.454
268    7.470
161    7.489
261    7.520
202    7.610
282    7.645
228    7.686
273    7.691
180    7.765
162    7.802
280    7.820
98     7.820
186    7.831
203    7.853
195    7.875
283    7.923
166    7.929
204    8.034
226    8.040
97     8.069
233    8.247
253    8.259
224    8.266
267    8.297
232    8.337
163    8.375
262    8.398
257    8.704
225    8.725
364    8.780
Name: RM, Length: 503, dtype: float64

In [23]:
df["RM"].sort_values(ascending=False)

364    8.780
225    8.725
257    8.704
262    8.398
163    8.375
232    8.337
267    8.297
224    8.266
253    8.259
233    8.247
97     8.069
226    8.040
204    8.034
166    7.929
283    7.923
195    7.875
203    7.853
186    7.831
98     7.820
280    7.820
162    7.802
180    7.765
273    7.691
228    7.686
282    7.645
202    7.610
261    7.520
161    7.489
268    7.470
256    7.454
       ...
389    5.390
362    5.362
403    5.349
209    5.344
417    5.304
477    5.304
385    5.277
156    5.272
148    5.186
413    5.155
490    5.093
392    5.036
141    5.019
152    5.012
387    5.000
310    4.973
368    4.970
366    4.963
147    4.926
373    4.906
144    4.903
388    4.880
386    4.652
412    4.628
414    4.519
384    4.368
406    4.138
374    4.138
367    3.863
365    3.561
Name: RM, Length: 503, dtype: float64

In [24]:
del df["ZN"]
df

,CRIM,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,test_data,flg
1,0.02731,7.07,0.0,NaN,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,test_data_val,1
3,0.03237,2.18,0.0,NaN,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,test_data_val,1
5,0.02985,2.18,0.0,NaN,6.430,58.7,6.0622,3.0,222.0,18.7,394.12,5.21,test_data_val,1
6,0.08829,7.87,0.0,0.524,6.012,66.6,5.5605,5.0,311.0,15.2,395.60,12.43,test_data_val,1
7,0.14455,7.87,0.0,0.524,6.172,96.1,5.9505,5.0,311.0,15.2,396.90,19.15,test_data_val,1
8,0.21124,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,15.2,386.63,29.93,test_data_val,1
9,0.17004,7.87,0.0,0.524,6.004,85.9,6.5921,5.0,311.0,15.2,386.71,17.10,test_data_val,1
10,0.22489,7.87,0.0,0.524,6.377,94.3,6.3467,5.0,311.0,15.2,392.52,20.45,test_data_val,1
11,0.11747,7.87,0.0,0.524,6.009,82.9,6.2267,5.0,311.0,15.2,396.90,13.27,test_data_val,1
12,0.09378,7.87,0.0,0.524,5.889,39.0,5.4509,5.0,311.0,15.2,390.50,15.71,test_data_val,1
13,0.62976,8.14,0.0,0.538,5.949,61.8,4.7075,4.0,307.0,21.0,396.90,8.26,test_data_val,1
14,0.63796,8.14,0.0,0.538,6.096,84.5,4.4619,4.0,307.0,21.0,380.02,10.26,test_data_val,1
15,0.62739,8.14,0.0,0.538,5.834,56.5,4.4986,4.0,307.0,21.0,395.62,8.47,test_data_val,1
16,1.05393,8.14,0.0,0.538,5.935,29.3,4.4986,4.0,307.0,21.0,386.85,6.58,test_data_val,1
17,0.78420,8.14,0.0,0.538,5.990,81.7,4.2579,4.0,307.0,21.0,386.75,14.67,test_data_val,1
18,0.80271,8.14,0.0,0.538,5.456,36.6,3.7965,4.0,307.0,21.0,288.99,11.69,test_data_val,1
19,0.72580,8.14,0.0,0.538,5.727,69.5,3.7965,4.0,307.0,21.0,390.95,11.28,test_data_val,1
20,1.25179,8.14,0.0,0.538,5.570,98.1,3.7979,4.0,307.0,21.0,376.57,21.02,test_data_val,1
21,0.85204,8.14,0.0,0.538,5.965,89.2,4.0123,4.0,307.0,21.0,392.53,13.83,test_data_val,1
22,1.23247,8.14,0.0,0.538,6.142,91.7,3.9769,4.0,307.0,21.0,396.90,18.72,test_data_val,1
23,0.98843,8.14,0.0,0.538,5.813,100.0,4.0952,4.0,307.0,21.0,394.54,19.88,test_data_val,1
24,0.75026,8.14,0.0,0.538,5.924,94.1,4.3996,4.0,307.0,21.0,394.33,16.30,test_data_val,1
25,0.84054,8.14,0.0,0.538,5.599,85.7,4.4546,4.0,307.0,21.0,303.42,16.51,test_data_val,1
26,0.67191,8.14,0.0,0.538,5.813,90.3,4.6820,4.0,307.0,21.0,376.88,14.81,test_data_val,1
27,0.95577,8.14,0.0,0.538,6.047,88.8,4.4534,4.0,307.0,21.0,306.38,17.28,test_data_val,1
28,0.77299,8.14,0.0,0.538,6.495,94.4,4.4547,4.0,307.0,21.0,387.94,12.80,test_data_val,1
29,1.00245,8.14,0.0,0.538,6.674,87.3,4.2390,4.0,307.0,21.0,380.23,11.98,test_data_val,1
30,1.13081,8.14,0.0,0.538,5.713,94.1,4.2330,4.0,307.0,21.0,360.17,22.60,test_data_val,1
31,1.35472,8.14,0.0,0.538,6.072,100.0,4.1750,4.0,307.0,21.0,376.73,13.04,test_data_val,1
32,1.38799,8.14,0.0,0.538,5.950,82.0,3.9900,4.0,307.0,21.0,232.60,27.71,test_data_val,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,4.87141,18.10,0.0,0.614,6.484,93.6,2.3053,24.0,666.0,20.2,396.21,18.68,test_data_val,1
477,15.02340,18.10,0.0,0.614,5.304,97.3,2.1007,24.0,666.0,20.2,349.48,24.91,test_data_val,1
478,10.23300,18.10,0.0,0.614,6.185,96.7,2.1705,24.0,666.0,20.2,379.70,18.03,test_data_val,1
479,14.33370,18.10,0.0,0.614,6.229,88.0,1.9512,24.0,666.0,20.2,383.32,13.11,test_data_val,1
480,5.82401,18.10,0.0,0.532,6.242,64.7,3.4242,24.0,666.0,20.2,396.90,10.74,test_data_val,1
481,5.70818,18.10,0.0,0.532,6.750,74.9,3.3317,24.0,666.0,20.2,393.07,7.74,test_data_val,1
482,5.73116,18.10,0.0,0.532,7.061,77.0,3.4106,24.0,666.0,20.2,395.28,7.01,test_data_val,1
483,2.81838,18.10,0.0,0.532,5.762,40.3,4.0983,24.0,666.0,20.2,392.92,10.42,test_data_val,1
484,2.37857,18.10,0.0,0.583,5.871,41.9,3.7240,24.0,666.0,20.2,370.73,13.34,test_data_val,1
485,3.67367,18.10,0.0,0.583,6.312,51.9,3.9917,24.0,666.0,20.2,388.62,10.58,test_data_val,1
486,5.69175,18.10,0.0,0.583,6.114,79.8,3.5459,24.0,666.0,20.2,392.68,14.98,test_data_val,1
487,4.83567,18.10,0.0,0.583,5.905,53.2,3.1523,24.0,666.0,20.2,388.22,11.45,test_data_val,1
488,0.15086,27.74,0.0,0.609,5.454,92.7,1.8209,4.0,711.0,20.1,395.09,18.06,test_data_val,1
489,0.18337,27.74,0.0,0.609,5.414,98.3,1.7554,4.0,711.0,20.1,344.05,23.97,test_data_val,1
490,0.20746,27.74,0.0,0.609,5.093,98.0,1.8226,4.0,711.0,20.1,318.43,29.68,test_data_val,1
491,0.10574,27.74,0.0,0.609,5.983,98.8,1.8681,4.0,711.0,20.1,390.11,18.07,test_data_val,1
492,0.11132,27.74,0.0,0.609,5.983,83.5,2.1099,4.0,711.0,20.1,396.90,13.35,test_data_val,1
493,0.17331,9.69,0.0,0.585,5.707,54.0,2.3817,6.0,391.0,19.2,396.90,12.01,test_data_val,1
494,0.27957,9.69,0.0,0.585,5.926,42.6,2.3817,6.0,391.0,19.2,396.90,13.59,test_data_val,1
495,0.17899,9.69,0.0,0.585,5.670,28.8,2.7986,6.0,391.0,19.2,393.29,17.60,test_data_val,1
496,0.28960,9.69,0.0,0.585,5.390,72.9,2.7986,6.0,391.0,19.2,396.90,21.14,test_data_val,1
497,0.26838,9.69,0.0,0.585,5.794,70.6,2.8927,6.0,391.0,19.2,396.90,14.10,test_data_val,1
498,0.23912,9.69,0.0,0.585,6.019,65.3,2.4091,6.0,391.0,19.2,396.90,12.92,test_data_val,1
499,0.17783,9.69,0.0,0.585,5.569,73.5,2.3999,6.0,391.0,19.2,395.77,15.10,test_data_val,1
500,0.22438,9.69,0.0,0.585,6.027,79.7,2.4982,6.0,391.0,19.2,396.90,14.33,test_data_val,1
501,0.06263,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67,test_data_val,1
502,0.04527,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,test_data_val,1
503,0.06076,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,test_data_val,1
504,0.10959,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,test_data_val,1
505,0.04741,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88,test_data_val,1

In [33]:
print(len(df["CHAS"]))
print(len(df.drop_duplicates(["CHAS"])))
df.drop_duplicates(["CHAS"]).head()

503
2

,CRIM,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,test_data,flg
1,0.02731,7.07,0.0,NaN,6.421,78.9,4.9671,2.0,242.0,17.8,396.9,9.14,test_data_val,1
142,3.32105,19.58,1.0,0.871,5.403,100.0,1.3216,5.0,403.0,14.7,396.9,26.82,test_data_val,1